# Generated by Django 5.1.3 on 2024-11-20 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_remove_marketfeature1_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketonetimeslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketonetimeslot',
            name='reserveCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketonetimeslot',
            name='totalReseve',
            field=models.IntegerField(verbose_name='تعداد کل رزرو'),
        ),
    ]
