# Generated by Django 5.1.3 on 2024-11-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_marketfeature1_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketfeature1',
            name='reserveCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketfeature2',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets_one', to='branch.marketfeature1'),
        ),
    ]
