# Generated by Django 5.1.3 on 2024-11-20 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_marketfeature1_reservecount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketfeature1',
            name='market',
        ),
        migrations.RemoveField(
            model_name='marketfeature1',
            name='reserveCount',
        ),
        migrations.AddField(
            model_name='marketonetimeslot',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketTimeSlots', to='branch.market'),
        ),
        migrations.AddField(
            model_name='marketonetimeslot',
            name='reserveCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketonetimeslot',
            name='totalReseve',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
